//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.06 at 09:25:01 AM CDT 
//


package com.ccighgo.service.transport.season.beans.assignstafftostate;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ccighgo.service.transport.season.beans.assignstafftostate package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AssignedStaffToState_QNAME = new QName("http://www.ccighgo.com/stafftostate", "AssignedStaffToState");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ccighgo.service.transport.season.beans.assignstafftostate
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AssignedStaffToState }
     * 
     */
    public AssignedStaffToState createAssignedStaffToState() {
        return new AssignedStaffToState();
    }

    /**
     * Create an instance of {@link StateFieldStaff }
     * 
     */
    public StateFieldStaff createStateFieldStaff() {
        return new StateFieldStaff();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AssignedStaffToState }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ccighgo.com/stafftostate", name = "AssignedStaffToState")
    public JAXBElement<AssignedStaffToState> createAssignedStaffToState(AssignedStaffToState value) {
        return new JAXBElement<AssignedStaffToState>(_AssignedStaffToState_QNAME, AssignedStaffToState.class, null, value);
    }

}
