//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.21 at 11:47:58 AM CST 
//


package com.ccighgo.service.transport.fieldstaff.beans.addnewschool;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FSAddNewSchoolGeneralInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FSAddNewSchoolGeneralInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="schoolName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="streetAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="zipCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="typeOfSchool" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tutionAmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isTheirReligiousAffiliation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="methodOfTravel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NoAcceptedFromCCI" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="enrollmentDeadlineForTheFall" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="acceptSeniors" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="webSite" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mailAddressSameAsPhysicalAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mailingAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mailingCity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mailingState" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mailingZipCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="studentBodySize" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="acceptSecondSemesterStudents" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="enrollmentDeadlineforSpring" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FSAddNewSchoolGeneralInfo", propOrder = {
    "schoolName",
    "phone",
    "streetAddress",
    "city",
    "state",
    "zipCode",
    "typeOfSchool",
    "tutionAmount",
    "isTheirReligiousAffiliation",
    "methodOfTravel",
    "noAcceptedFromCCI",
    "enrollmentDeadlineForTheFall",
    "acceptSeniors",
    "webSite",
    "mailAddressSameAsPhysicalAddress",
    "mailingAddress",
    "mailingCity",
    "mailingState",
    "mailingZipCode",
    "studentBodySize",
    "acceptSecondSemesterStudents",
    "enrollmentDeadlineforSpring"
})
public class FSAddNewSchoolGeneralInfo {

    @XmlElement(required = true)
    protected String schoolName;
    @XmlElement(required = true)
    protected String phone;
    @XmlElement(required = true)
    protected String streetAddress;
    @XmlElement(required = true)
    protected String city;
    @XmlElement(required = true)
    protected String state;
    @XmlElement(required = true)
    protected String zipCode;
    @XmlElement(required = true)
    protected String typeOfSchool;
    @XmlElement(required = true)
    protected String tutionAmount;
    @XmlElement(required = true)
    protected String isTheirReligiousAffiliation;
    @XmlElement(required = true)
    protected String methodOfTravel;
    @XmlElement(name = "NoAcceptedFromCCI", required = true)
    protected String noAcceptedFromCCI;
    @XmlElement(required = true)
    protected String enrollmentDeadlineForTheFall;
    @XmlElement(required = true)
    protected String acceptSeniors;
    @XmlElement(required = true)
    protected String webSite;
    @XmlElement(required = true)
    protected String mailAddressSameAsPhysicalAddress;
    @XmlElement(required = true)
    protected String mailingAddress;
    @XmlElement(required = true)
    protected String mailingCity;
    @XmlElement(required = true)
    protected String mailingState;
    @XmlElement(required = true)
    protected String mailingZipCode;
    @XmlElement(required = true)
    protected String studentBodySize;
    @XmlElement(required = true)
    protected String acceptSecondSemesterStudents;
    @XmlElement(required = true)
    protected String enrollmentDeadlineforSpring;

    /**
     * Gets the value of the schoolName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * Sets the value of the schoolName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchoolName(String value) {
        this.schoolName = value;
    }

    /**
     * Gets the value of the phone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhone(String value) {
        this.phone = value;
    }

    /**
     * Gets the value of the streetAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetAddress() {
        return streetAddress;
    }

    /**
     * Sets the value of the streetAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetAddress(String value) {
        this.streetAddress = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the zipCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * Sets the value of the zipCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZipCode(String value) {
        this.zipCode = value;
    }

    /**
     * Gets the value of the typeOfSchool property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeOfSchool() {
        return typeOfSchool;
    }

    /**
     * Sets the value of the typeOfSchool property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeOfSchool(String value) {
        this.typeOfSchool = value;
    }

    /**
     * Gets the value of the tutionAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTutionAmount() {
        return tutionAmount;
    }

    /**
     * Sets the value of the tutionAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTutionAmount(String value) {
        this.tutionAmount = value;
    }

    /**
     * Gets the value of the isTheirReligiousAffiliation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsTheirReligiousAffiliation() {
        return isTheirReligiousAffiliation;
    }

    /**
     * Sets the value of the isTheirReligiousAffiliation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsTheirReligiousAffiliation(String value) {
        this.isTheirReligiousAffiliation = value;
    }

    /**
     * Gets the value of the methodOfTravel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMethodOfTravel() {
        return methodOfTravel;
    }

    /**
     * Sets the value of the methodOfTravel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMethodOfTravel(String value) {
        this.methodOfTravel = value;
    }

    /**
     * Gets the value of the noAcceptedFromCCI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoAcceptedFromCCI() {
        return noAcceptedFromCCI;
    }

    /**
     * Sets the value of the noAcceptedFromCCI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoAcceptedFromCCI(String value) {
        this.noAcceptedFromCCI = value;
    }

    /**
     * Gets the value of the enrollmentDeadlineForTheFall property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnrollmentDeadlineForTheFall() {
        return enrollmentDeadlineForTheFall;
    }

    /**
     * Sets the value of the enrollmentDeadlineForTheFall property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnrollmentDeadlineForTheFall(String value) {
        this.enrollmentDeadlineForTheFall = value;
    }

    /**
     * Gets the value of the acceptSeniors property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcceptSeniors() {
        return acceptSeniors;
    }

    /**
     * Sets the value of the acceptSeniors property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcceptSeniors(String value) {
        this.acceptSeniors = value;
    }

    /**
     * Gets the value of the webSite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebSite() {
        return webSite;
    }

    /**
     * Sets the value of the webSite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebSite(String value) {
        this.webSite = value;
    }

    /**
     * Gets the value of the mailAddressSameAsPhysicalAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMailAddressSameAsPhysicalAddress() {
        return mailAddressSameAsPhysicalAddress;
    }

    /**
     * Sets the value of the mailAddressSameAsPhysicalAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMailAddressSameAsPhysicalAddress(String value) {
        this.mailAddressSameAsPhysicalAddress = value;
    }

    /**
     * Gets the value of the mailingAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMailingAddress() {
        return mailingAddress;
    }

    /**
     * Sets the value of the mailingAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMailingAddress(String value) {
        this.mailingAddress = value;
    }

    /**
     * Gets the value of the mailingCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMailingCity() {
        return mailingCity;
    }

    /**
     * Sets the value of the mailingCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMailingCity(String value) {
        this.mailingCity = value;
    }

    /**
     * Gets the value of the mailingState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMailingState() {
        return mailingState;
    }

    /**
     * Sets the value of the mailingState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMailingState(String value) {
        this.mailingState = value;
    }

    /**
     * Gets the value of the mailingZipCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMailingZipCode() {
        return mailingZipCode;
    }

    /**
     * Sets the value of the mailingZipCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMailingZipCode(String value) {
        this.mailingZipCode = value;
    }

    /**
     * Gets the value of the studentBodySize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStudentBodySize() {
        return studentBodySize;
    }

    /**
     * Sets the value of the studentBodySize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStudentBodySize(String value) {
        this.studentBodySize = value;
    }

    /**
     * Gets the value of the acceptSecondSemesterStudents property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcceptSecondSemesterStudents() {
        return acceptSecondSemesterStudents;
    }

    /**
     * Sets the value of the acceptSecondSemesterStudents property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcceptSecondSemesterStudents(String value) {
        this.acceptSecondSemesterStudents = value;
    }

    /**
     * Gets the value of the enrollmentDeadlineforSpring property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnrollmentDeadlineforSpring() {
        return enrollmentDeadlineforSpring;
    }

    /**
     * Sets the value of the enrollmentDeadlineforSpring property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnrollmentDeadlineforSpring(String value) {
        this.enrollmentDeadlineforSpring = value;
    }

}
