//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.15 at 05:46:43 PM CDT 
//


package com.ccighgo.service.transport.season.beans.seasonhspj1hsdetails;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for J1HSAugStart complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="J1HSAugStart">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="seasonId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="seasonProgramId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="augFirstSemStartDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="augFirstSemEndDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="augFirstSemApplDeadlineDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="augFirstSemEarliestBirthDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="augFirstSemLatestDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="showAugFirstSemToNewHF" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ativateAugFullYearProgram" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="augFullYrStartDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="augFullYrEndDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="augFulllYrApplDeadlineDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="showAugFullYrToNewHF" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "J1HSAugStart", propOrder = {
    "seasonId",
    "seasonProgramId",
    "augFirstSemStartDate",
    "augFirstSemEndDate",
    "augFirstSemApplDeadlineDate",
    "augFirstSemEarliestBirthDate",
    "augFirstSemLatestDate",
    "showAugFirstSemToNewHF",
    "ativateAugFullYearProgram",
    "augFullYrStartDate",
    "augFullYrEndDate",
    "augFulllYrApplDeadlineDate",
    "showAugFullYrToNewHF"
})
public class J1HSAugStart {

    protected int seasonId;
    protected int seasonProgramId;
    protected String augFirstSemStartDate;
    protected String augFirstSemEndDate;
    protected String augFirstSemApplDeadlineDate;
    protected String augFirstSemEarliestBirthDate;
    protected String augFirstSemLatestDate;
    protected Boolean showAugFirstSemToNewHF;
    protected Boolean ativateAugFullYearProgram;
    protected String augFullYrStartDate;
    protected String augFullYrEndDate;
    protected String augFulllYrApplDeadlineDate;
    protected Boolean showAugFullYrToNewHF;

    /**
     * Gets the value of the seasonId property.
     * 
     */
    public int getSeasonId() {
        return seasonId;
    }

    /**
     * Sets the value of the seasonId property.
     * 
     */
    public void setSeasonId(int value) {
        this.seasonId = value;
    }

    /**
     * Gets the value of the seasonProgramId property.
     * 
     */
    public int getSeasonProgramId() {
        return seasonProgramId;
    }

    /**
     * Sets the value of the seasonProgramId property.
     * 
     */
    public void setSeasonProgramId(int value) {
        this.seasonProgramId = value;
    }

    /**
     * Gets the value of the augFirstSemStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAugFirstSemStartDate() {
        return augFirstSemStartDate;
    }

    /**
     * Sets the value of the augFirstSemStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAugFirstSemStartDate(String value) {
        this.augFirstSemStartDate = value;
    }

    /**
     * Gets the value of the augFirstSemEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAugFirstSemEndDate() {
        return augFirstSemEndDate;
    }

    /**
     * Sets the value of the augFirstSemEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAugFirstSemEndDate(String value) {
        this.augFirstSemEndDate = value;
    }

    /**
     * Gets the value of the augFirstSemApplDeadlineDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAugFirstSemApplDeadlineDate() {
        return augFirstSemApplDeadlineDate;
    }

    /**
     * Sets the value of the augFirstSemApplDeadlineDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAugFirstSemApplDeadlineDate(String value) {
        this.augFirstSemApplDeadlineDate = value;
    }

    /**
     * Gets the value of the augFirstSemEarliestBirthDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAugFirstSemEarliestBirthDate() {
        return augFirstSemEarliestBirthDate;
    }

    /**
     * Sets the value of the augFirstSemEarliestBirthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAugFirstSemEarliestBirthDate(String value) {
        this.augFirstSemEarliestBirthDate = value;
    }

    /**
     * Gets the value of the augFirstSemLatestDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAugFirstSemLatestDate() {
        return augFirstSemLatestDate;
    }

    /**
     * Sets the value of the augFirstSemLatestDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAugFirstSemLatestDate(String value) {
        this.augFirstSemLatestDate = value;
    }

    /**
     * Gets the value of the showAugFirstSemToNewHF property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowAugFirstSemToNewHF() {
        return showAugFirstSemToNewHF;
    }

    /**
     * Sets the value of the showAugFirstSemToNewHF property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowAugFirstSemToNewHF(Boolean value) {
        this.showAugFirstSemToNewHF = value;
    }

    /**
     * Gets the value of the ativateAugFullYearProgram property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAtivateAugFullYearProgram() {
        return ativateAugFullYearProgram;
    }

    /**
     * Sets the value of the ativateAugFullYearProgram property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAtivateAugFullYearProgram(Boolean value) {
        this.ativateAugFullYearProgram = value;
    }

    /**
     * Gets the value of the augFullYrStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAugFullYrStartDate() {
        return augFullYrStartDate;
    }

    /**
     * Sets the value of the augFullYrStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAugFullYrStartDate(String value) {
        this.augFullYrStartDate = value;
    }

    /**
     * Gets the value of the augFullYrEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAugFullYrEndDate() {
        return augFullYrEndDate;
    }

    /**
     * Sets the value of the augFullYrEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAugFullYrEndDate(String value) {
        this.augFullYrEndDate = value;
    }

    /**
     * Gets the value of the augFulllYrApplDeadlineDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAugFulllYrApplDeadlineDate() {
        return augFulllYrApplDeadlineDate;
    }

    /**
     * Sets the value of the augFulllYrApplDeadlineDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAugFulllYrApplDeadlineDate(String value) {
        this.augFulllYrApplDeadlineDate = value;
    }

    /**
     * Gets the value of the showAugFullYrToNewHF property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowAugFullYrToNewHF() {
        return showAugFullYrToNewHF;
    }

    /**
     * Sets the value of the showAugFullYrToNewHF property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowAugFullYrToNewHF(Boolean value) {
        this.showAugFullYrToNewHF = value;
    }

}
