//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.11 at 03:30:17 PM CST 
//


package gov.ice.xmlschema.sevisbatch.exchangevisitor;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * A TIPP site of activity with phases
 * 
 * <p>Java class for TippSiteWithPhases complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TippSiteWithPhases">
 *   &lt;complexContent>
 *     &lt;extension base="{}TippSite">
 *       &lt;sequence>
 *         &lt;element name="TippPhase" type="{}TippPhase" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TippSiteWithPhases", propOrder = {
    "tippPhase"
})
@XmlSeeAlso({
    gov.ice.xmlschema.sevisbatch.exchangevisitor.SEVISEVBatchType.UpdateEV.ExchangeVisitor.TIPP.AddSite.class
})
public class TippSiteWithPhases
    extends TippSite
{

    @XmlElement(name = "TippPhase", required = true)
    protected List<TippPhase> tippPhase;

    /**
     * Gets the value of the tippPhase property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tippPhase property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTippPhase().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TippPhase }
     * 
     * 
     */
    public List<TippPhase> getTippPhase() {
        if (tippPhase == null) {
            tippPhase = new ArrayList<TippPhase>();
        }
        return this.tippPhase;
    }

}
