//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.27 at 05:47:44 PM CDT 
//


package com.ccighgo.service.transport.season.beans.seasondepartdoc;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ccighgo.service.transport.season.beans.seasondepartdoc package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SeasonDepartmentDocument_QNAME = new QName("http://www.ccighgo.com/seasondepartdoc", "SeasonDepartmentDocument");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ccighgo.service.transport.season.beans.seasondepartdoc
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SeasonDepartmentDocument }
     * 
     */
    public SeasonDepartmentDocument createSeasonDepartmentDocument() {
        return new SeasonDepartmentDocument();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SeasonDepartmentDocument }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ccighgo.com/seasondepartdoc", name = "SeasonDepartmentDocument")
    public JAXBElement<SeasonDepartmentDocument> createSeasonDepartmentDocument(SeasonDepartmentDocument value) {
        return new JAXBElement<SeasonDepartmentDocument>(_SeasonDepartmentDocument_QNAME, SeasonDepartmentDocument.class, null, value);
    }

}
