//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.03 at 03:47:38 PM CDT 
//


package com.ccighgo.service.transport.partner.beans.hfHostAgainQuestion;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ccighgo.service.transport.partner.beans.hfHostAgainQuestion package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _HFHostAgainQuestion_QNAME = new QName("http://www.ccighgo.com/hfHostAgainQuestion", "HFHostAgainQuestion");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ccighgo.service.transport.partner.beans.hfHostAgainQuestion
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HFHostAgainQuestionDetail }
     * 
     */
    public HFHostAgainQuestionDetail createHFHostAgainQuestionDetail() {
        return new HFHostAgainQuestionDetail();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HFHostAgainQuestionDetail }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ccighgo.com/hfHostAgainQuestion", name = "HFHostAgainQuestion")
    public JAXBElement<HFHostAgainQuestionDetail> createHFHostAgainQuestion(HFHostAgainQuestionDetail value) {
        return new JAXBElement<HFHostAgainQuestionDetail>(_HFHostAgainQuestion_QNAME, HFHostAgainQuestionDetail.class, null, value);
    }

}
