//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.15 at 04:27:36 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ccighgo.com/hfcommunityandschoolpage")
package com.ccighgo.service.transport.hostfamily.beans.application.hfcommunityandschoolpage;
