//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.01 at 04:52:31 PM CST 
//


package com.ccighgo.service.transport.utility.beans.partner.status;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PartnerStatus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PartnerStatus">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="partnerStatusId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="partnerStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PartnerStatus", propOrder = {
    "partnerStatusId",
    "partnerStatus"
})
public class PartnerStatus {

    protected int partnerStatusId;
    @XmlElement(required = true)
    protected String partnerStatus;

    /**
     * Gets the value of the partnerStatusId property.
     * 
     */
    public int getPartnerStatusId() {
        return partnerStatusId;
    }

    /**
     * Sets the value of the partnerStatusId property.
     * 
     */
    public void setPartnerStatusId(int value) {
        this.partnerStatusId = value;
    }

    /**
     * Gets the value of the partnerStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnerStatus() {
        return partnerStatus;
    }

    /**
     * Sets the value of the partnerStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnerStatus(String value) {
        this.partnerStatus = value;
    }

}
