//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.26 at 02:53:37 PM CDT 
//


package com.ccighgo.service.transport.seasons.beans.backgroundcheck;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PostBackURL">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="CredentialType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="BackgroundSearchPackage">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ReferenceId">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="IdValue">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="PersonalData">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="PersonName" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="GivenName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="MiddleName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="FamilyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Affix" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;simpleContent>
 *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                               &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/extension>
 *                                           &lt;/simpleContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="PostalAddress">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="CountryCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Region" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Municipality" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="DeliveryAddress">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="StreetName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="ContactMethod" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Use" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="Telephone" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="FormattedNumber" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="InternetEmailAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="DemographicDetail">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="GovernmentId">
 *                                         &lt;complexType>
 *                                           &lt;simpleContent>
 *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                               &lt;attribute name="countryCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="issuingAuthority" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="documentType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/extension>
 *                                           &lt;/simpleContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="DateOfBirth" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                                       &lt;element name="DLState" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="DLNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Screenings">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="AdditionalItems">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="qualifier" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="action" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="account" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PackageNbr" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "postBackURL",
    "backgroundSearchPackage"
})
@XmlRootElement(name = "BackgroundCheck")
public class BackgroundCheck {

    @XmlElement(name = "PostBackURL", required = true)
    protected BackgroundCheck.PostBackURL postBackURL;
    @XmlElement(name = "BackgroundSearchPackage", required = true)
    protected BackgroundCheck.BackgroundSearchPackage backgroundSearchPackage;
    @XmlAttribute(name = "account")
    protected String account;
    @XmlAttribute(name = "PackageNbr")
    protected Byte packageNbr;

    /**
     * Gets the value of the postBackURL property.
     * 
     * @return
     *     possible object is
     *     {@link BackgroundCheck.PostBackURL }
     *     
     */
    public BackgroundCheck.PostBackURL getPostBackURL() {
        return postBackURL;
    }

    /**
     * Sets the value of the postBackURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link BackgroundCheck.PostBackURL }
     *     
     */
    public void setPostBackURL(BackgroundCheck.PostBackURL value) {
        this.postBackURL = value;
    }

    /**
     * Gets the value of the backgroundSearchPackage property.
     * 
     * @return
     *     possible object is
     *     {@link BackgroundCheck.BackgroundSearchPackage }
     *     
     */
    public BackgroundCheck.BackgroundSearchPackage getBackgroundSearchPackage() {
        return backgroundSearchPackage;
    }

    /**
     * Sets the value of the backgroundSearchPackage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BackgroundCheck.BackgroundSearchPackage }
     *     
     */
    public void setBackgroundSearchPackage(BackgroundCheck.BackgroundSearchPackage value) {
        this.backgroundSearchPackage = value;
    }

    /**
     * Gets the value of the account property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccount() {
        return account;
    }

    /**
     * Sets the value of the account property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccount(String value) {
        this.account = value;
    }

    /**
     * Gets the value of the packageNbr property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getPackageNbr() {
        return packageNbr;
    }

    /**
     * Sets the value of the packageNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setPackageNbr(Byte value) {
        this.packageNbr = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ReferenceId">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="IdValue">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="PersonalData">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="PersonName" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="GivenName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="MiddleName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="FamilyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Affix" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;simpleContent>
     *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                                     &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/extension>
     *                                 &lt;/simpleContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="PostalAddress">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="CountryCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Region" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Municipality" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="DeliveryAddress">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="StreetName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="ContactMethod" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Use" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="Telephone" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="FormattedNumber" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="InternetEmailAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="DemographicDetail">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="GovernmentId">
     *                               &lt;complexType>
     *                                 &lt;simpleContent>
     *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                                     &lt;attribute name="countryCode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="issuingAuthority" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="documentType" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/extension>
     *                                 &lt;/simpleContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="DateOfBirth" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *                             &lt;element name="DLState" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="DLNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Screenings">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="AdditionalItems">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Text" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                           &lt;attribute name="qualifier" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="action" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "referenceId",
        "personalData",
        "screenings"
    })
    public static class BackgroundSearchPackage {

        @XmlElement(name = "ReferenceId", required = true)
        protected BackgroundCheck.BackgroundSearchPackage.ReferenceId referenceId;
        @XmlElement(name = "PersonalData", required = true)
        protected BackgroundCheck.BackgroundSearchPackage.PersonalData personalData;
        @XmlElement(name = "Screenings", required = true)
        protected BackgroundCheck.BackgroundSearchPackage.Screenings screenings;
        @XmlAttribute(name = "action")
        protected String action;

        /**
         * Gets the value of the referenceId property.
         * 
         * @return
         *     possible object is
         *     {@link BackgroundCheck.BackgroundSearchPackage.ReferenceId }
         *     
         */
        public BackgroundCheck.BackgroundSearchPackage.ReferenceId getReferenceId() {
            return referenceId;
        }

        /**
         * Sets the value of the referenceId property.
         * 
         * @param value
         *     allowed object is
         *     {@link BackgroundCheck.BackgroundSearchPackage.ReferenceId }
         *     
         */
        public void setReferenceId(BackgroundCheck.BackgroundSearchPackage.ReferenceId value) {
            this.referenceId = value;
        }

        /**
         * Gets the value of the personalData property.
         * 
         * @return
         *     possible object is
         *     {@link BackgroundCheck.BackgroundSearchPackage.PersonalData }
         *     
         */
        public BackgroundCheck.BackgroundSearchPackage.PersonalData getPersonalData() {
            return personalData;
        }

        /**
         * Sets the value of the personalData property.
         * 
         * @param value
         *     allowed object is
         *     {@link BackgroundCheck.BackgroundSearchPackage.PersonalData }
         *     
         */
        public void setPersonalData(BackgroundCheck.BackgroundSearchPackage.PersonalData value) {
            this.personalData = value;
        }

        /**
         * Gets the value of the screenings property.
         * 
         * @return
         *     possible object is
         *     {@link BackgroundCheck.BackgroundSearchPackage.Screenings }
         *     
         */
        public BackgroundCheck.BackgroundSearchPackage.Screenings getScreenings() {
            return screenings;
        }

        /**
         * Sets the value of the screenings property.
         * 
         * @param value
         *     allowed object is
         *     {@link BackgroundCheck.BackgroundSearchPackage.Screenings }
         *     
         */
        public void setScreenings(BackgroundCheck.BackgroundSearchPackage.Screenings value) {
            this.screenings = value;
        }

        /**
         * Gets the value of the action property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAction() {
            return action;
        }

        /**
         * Sets the value of the action property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAction(String value) {
            this.action = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="PersonName" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="GivenName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="MiddleName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="FamilyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Affix" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;simpleContent>
         *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/extension>
         *                       &lt;/simpleContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="PostalAddress">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="CountryCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Region" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Municipality" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="DeliveryAddress">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="StreetName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="ContactMethod" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Use" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="Telephone" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="FormattedNumber" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="InternetEmailAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="DemographicDetail">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="GovernmentId">
         *                     &lt;complexType>
         *                       &lt;simpleContent>
         *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                           &lt;attribute name="countryCode" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="issuingAuthority" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="documentType" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/extension>
         *                       &lt;/simpleContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="DateOfBirth" type="{http://www.w3.org/2001/XMLSchema}date"/>
         *                   &lt;element name="DLState" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="DLNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "personName",
            "postalAddress",
            "contactMethod",
            "demographicDetail"
        })
        public static class PersonalData {

            @XmlElement(name = "PersonName")
            protected List<BackgroundCheck.BackgroundSearchPackage.PersonalData.PersonName> personName;
            @XmlElement(name = "PostalAddress", required = true)
            protected BackgroundCheck.BackgroundSearchPackage.PersonalData.PostalAddress postalAddress;
            @XmlElement(name = "ContactMethod")
            protected List<BackgroundCheck.BackgroundSearchPackage.PersonalData.ContactMethod> contactMethod;
            @XmlElement(name = "DemographicDetail", required = true)
            protected BackgroundCheck.BackgroundSearchPackage.PersonalData.DemographicDetail demographicDetail;

            /**
             * Gets the value of the personName property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the personName property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPersonName().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link BackgroundCheck.BackgroundSearchPackage.PersonalData.PersonName }
             * 
             * 
             */
            public List<BackgroundCheck.BackgroundSearchPackage.PersonalData.PersonName> getPersonName() {
                if (personName == null) {
                    personName = new ArrayList<BackgroundCheck.BackgroundSearchPackage.PersonalData.PersonName>();
                }
                return this.personName;
            }

            /**
             * Gets the value of the postalAddress property.
             * 
             * @return
             *     possible object is
             *     {@link BackgroundCheck.BackgroundSearchPackage.PersonalData.PostalAddress }
             *     
             */
            public BackgroundCheck.BackgroundSearchPackage.PersonalData.PostalAddress getPostalAddress() {
                return postalAddress;
            }

            /**
             * Sets the value of the postalAddress property.
             * 
             * @param value
             *     allowed object is
             *     {@link BackgroundCheck.BackgroundSearchPackage.PersonalData.PostalAddress }
             *     
             */
            public void setPostalAddress(BackgroundCheck.BackgroundSearchPackage.PersonalData.PostalAddress value) {
                this.postalAddress = value;
            }

            /**
             * Gets the value of the contactMethod property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the contactMethod property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getContactMethod().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link BackgroundCheck.BackgroundSearchPackage.PersonalData.ContactMethod }
             * 
             * 
             */
            public List<BackgroundCheck.BackgroundSearchPackage.PersonalData.ContactMethod> getContactMethod() {
                if (contactMethod == null) {
                    contactMethod = new ArrayList<BackgroundCheck.BackgroundSearchPackage.PersonalData.ContactMethod>();
                }
                return this.contactMethod;
            }

            /**
             * Gets the value of the demographicDetail property.
             * 
             * @return
             *     possible object is
             *     {@link BackgroundCheck.BackgroundSearchPackage.PersonalData.DemographicDetail }
             *     
             */
            public BackgroundCheck.BackgroundSearchPackage.PersonalData.DemographicDetail getDemographicDetail() {
                return demographicDetail;
            }

            /**
             * Sets the value of the demographicDetail property.
             * 
             * @param value
             *     allowed object is
             *     {@link BackgroundCheck.BackgroundSearchPackage.PersonalData.DemographicDetail }
             *     
             */
            public void setDemographicDetail(BackgroundCheck.BackgroundSearchPackage.PersonalData.DemographicDetail value) {
                this.demographicDetail = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Use" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="Telephone" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="FormattedNumber" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="InternetEmailAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "use",
                "telephone",
                "internetEmailAddress"
            })
            public static class ContactMethod {

                @XmlElement(name = "Use")
                protected String use;
                @XmlElement(name = "Telephone")
                protected BackgroundCheck.BackgroundSearchPackage.PersonalData.ContactMethod.Telephone telephone;
                @XmlElement(name = "InternetEmailAddress")
                protected String internetEmailAddress;

                /**
                 * Gets the value of the use property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUse() {
                    return use;
                }

                /**
                 * Sets the value of the use property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUse(String value) {
                    this.use = value;
                }

                /**
                 * Gets the value of the telephone property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BackgroundCheck.BackgroundSearchPackage.PersonalData.ContactMethod.Telephone }
                 *     
                 */
                public BackgroundCheck.BackgroundSearchPackage.PersonalData.ContactMethod.Telephone getTelephone() {
                    return telephone;
                }

                /**
                 * Sets the value of the telephone property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BackgroundCheck.BackgroundSearchPackage.PersonalData.ContactMethod.Telephone }
                 *     
                 */
                public void setTelephone(BackgroundCheck.BackgroundSearchPackage.PersonalData.ContactMethod.Telephone value) {
                    this.telephone = value;
                }

                /**
                 * Gets the value of the internetEmailAddress property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getInternetEmailAddress() {
                    return internetEmailAddress;
                }

                /**
                 * Sets the value of the internetEmailAddress property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setInternetEmailAddress(String value) {
                    this.internetEmailAddress = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="FormattedNumber" type="{http://www.w3.org/2001/XMLSchema}long"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "formattedNumber"
                })
                public static class Telephone {

                    @XmlElement(name = "FormattedNumber")
                    protected long formattedNumber;

                    /**
                     * Gets the value of the formattedNumber property.
                     * 
                     */
                    public long getFormattedNumber() {
                        return formattedNumber;
                    }

                    /**
                     * Sets the value of the formattedNumber property.
                     * 
                     */
                    public void setFormattedNumber(long value) {
                        this.formattedNumber = value;
                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="GovernmentId">
             *           &lt;complexType>
             *             &lt;simpleContent>
             *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *                 &lt;attribute name="countryCode" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="issuingAuthority" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="documentType" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/extension>
             *             &lt;/simpleContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="DateOfBirth" type="{http://www.w3.org/2001/XMLSchema}date"/>
             *         &lt;element name="DLState" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="DLNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "governmentId",
                "dateOfBirth",
                "dlState",
                "dlNumber"
            })
            public static class DemographicDetail {

                @XmlElement(name = "GovernmentId", required = true)
                protected BackgroundCheck.BackgroundSearchPackage.PersonalData.DemographicDetail.GovernmentId governmentId;
                @XmlElement(name = "DateOfBirth", required = true)
                @XmlSchemaType(name = "date")
                protected XMLGregorianCalendar dateOfBirth;
                @XmlElement(name = "DLState", required = true)
                protected String dlState;
                @XmlElement(name = "DLNumber", required = true)
                protected String dlNumber;

                /**
                 * Gets the value of the governmentId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BackgroundCheck.BackgroundSearchPackage.PersonalData.DemographicDetail.GovernmentId }
                 *     
                 */
                public BackgroundCheck.BackgroundSearchPackage.PersonalData.DemographicDetail.GovernmentId getGovernmentId() {
                    return governmentId;
                }

                /**
                 * Sets the value of the governmentId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BackgroundCheck.BackgroundSearchPackage.PersonalData.DemographicDetail.GovernmentId }
                 *     
                 */
                public void setGovernmentId(BackgroundCheck.BackgroundSearchPackage.PersonalData.DemographicDetail.GovernmentId value) {
                    this.governmentId = value;
                }

                /**
                 * Gets the value of the dateOfBirth property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getDateOfBirth() {
                    return dateOfBirth;
                }

                /**
                 * Sets the value of the dateOfBirth property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setDateOfBirth(XMLGregorianCalendar value) {
                    this.dateOfBirth = value;
                }

                /**
                 * Gets the value of the dlState property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDLState() {
                    return dlState;
                }

                /**
                 * Sets the value of the dlState property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDLState(String value) {
                    this.dlState = value;
                }

                /**
                 * Gets the value of the dlNumber property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDLNumber() {
                    return dlNumber;
                }

                /**
                 * Sets the value of the dlNumber property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDLNumber(String value) {
                    this.dlNumber = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;simpleContent>
                 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                 *       &lt;attribute name="countryCode" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="issuingAuthority" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="documentType" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/extension>
                 *   &lt;/simpleContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "value"
                })
                public static class GovernmentId {

                    @XmlValue
                    protected String value;
                    @XmlAttribute(name = "countryCode")
                    protected String countryCode;
                    @XmlAttribute(name = "issuingAuthority")
                    protected String issuingAuthority;
                    @XmlAttribute(name = "documentType")
                    protected String documentType;

                    /**
                     * Gets the value of the value property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setValue(String value) {
                        this.value = value;
                    }

                    /**
                     * Gets the value of the countryCode property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getCountryCode() {
                        return countryCode;
                    }

                    /**
                     * Sets the value of the countryCode property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setCountryCode(String value) {
                        this.countryCode = value;
                    }

                    /**
                     * Gets the value of the issuingAuthority property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getIssuingAuthority() {
                        return issuingAuthority;
                    }

                    /**
                     * Sets the value of the issuingAuthority property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setIssuingAuthority(String value) {
                        this.issuingAuthority = value;
                    }

                    /**
                     * Gets the value of the documentType property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getDocumentType() {
                        return documentType;
                    }

                    /**
                     * Sets the value of the documentType property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setDocumentType(String value) {
                        this.documentType = value;
                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="GivenName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="MiddleName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="FamilyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Affix" minOccurs="0">
             *           &lt;complexType>
             *             &lt;simpleContent>
             *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/extension>
             *             &lt;/simpleContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "givenName",
                "middleName",
                "familyName",
                "affix"
            })
            public static class PersonName {

                @XmlElement(name = "GivenName", required = true)
                protected String givenName;
                @XmlElement(name = "MiddleName", required = true)
                protected String middleName;
                @XmlElement(name = "FamilyName", required = true)
                protected String familyName;
                @XmlElement(name = "Affix")
                protected BackgroundCheck.BackgroundSearchPackage.PersonalData.PersonName.Affix affix;
                @XmlAttribute(name = "type")
                protected String type;

                /**
                 * Gets the value of the givenName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getGivenName() {
                    return givenName;
                }

                /**
                 * Sets the value of the givenName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setGivenName(String value) {
                    this.givenName = value;
                }

                /**
                 * Gets the value of the middleName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMiddleName() {
                    return middleName;
                }

                /**
                 * Sets the value of the middleName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMiddleName(String value) {
                    this.middleName = value;
                }

                /**
                 * Gets the value of the familyName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFamilyName() {
                    return familyName;
                }

                /**
                 * Sets the value of the familyName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFamilyName(String value) {
                    this.familyName = value;
                }

                /**
                 * Gets the value of the affix property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BackgroundCheck.BackgroundSearchPackage.PersonalData.PersonName.Affix }
                 *     
                 */
                public BackgroundCheck.BackgroundSearchPackage.PersonalData.PersonName.Affix getAffix() {
                    return affix;
                }

                /**
                 * Sets the value of the affix property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BackgroundCheck.BackgroundSearchPackage.PersonalData.PersonName.Affix }
                 *     
                 */
                public void setAffix(BackgroundCheck.BackgroundSearchPackage.PersonalData.PersonName.Affix value) {
                    this.affix = value;
                }

                /**
                 * Gets the value of the type property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getType() {
                    return type;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setType(String value) {
                    this.type = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;simpleContent>
                 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/extension>
                 *   &lt;/simpleContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "value"
                })
                public static class Affix {

                    @XmlValue
                    protected String value;
                    @XmlAttribute(name = "type")
                    protected String type;

                    /**
                     * Gets the value of the value property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setValue(String value) {
                        this.value = value;
                    }

                    /**
                     * Gets the value of the type property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getType() {
                        return type;
                    }

                    /**
                     * Sets the value of the type property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setType(String value) {
                        this.type = value;
                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="CountryCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Region" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Municipality" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="DeliveryAddress">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="StreetName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "countryCode",
                "postalCode",
                "region",
                "municipality",
                "deliveryAddress"
            })
            public static class PostalAddress {

                @XmlElement(name = "CountryCode", required = true)
                protected String countryCode;
                @XmlElement(name = "PostalCode", required = true)
                protected String postalCode;
                @XmlElement(name = "Region", required = true)
                protected String region;
                @XmlElement(name = "Municipality", required = true)
                protected String municipality;
                @XmlElement(name = "DeliveryAddress", required = true)
                protected BackgroundCheck.BackgroundSearchPackage.PersonalData.PostalAddress.DeliveryAddress deliveryAddress;
                @XmlAttribute(name = "type")
                protected String type;

                /**
                 * Gets the value of the countryCode property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCountryCode() {
                    return countryCode;
                }

                /**
                 * Sets the value of the countryCode property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCountryCode(String value) {
                    this.countryCode = value;
                }

                /**
                 * Gets the value of the postalCode property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPostalCode() {
                    return postalCode;
                }

                /**
                 * Sets the value of the postalCode property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPostalCode(String value) {
                    this.postalCode = value;
                }

                /**
                 * Gets the value of the region property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRegion() {
                    return region;
                }

                /**
                 * Sets the value of the region property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRegion(String value) {
                    this.region = value;
                }

                /**
                 * Gets the value of the municipality property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMunicipality() {
                    return municipality;
                }

                /**
                 * Sets the value of the municipality property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMunicipality(String value) {
                    this.municipality = value;
                }

                /**
                 * Gets the value of the deliveryAddress property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BackgroundCheck.BackgroundSearchPackage.PersonalData.PostalAddress.DeliveryAddress }
                 *     
                 */
                public BackgroundCheck.BackgroundSearchPackage.PersonalData.PostalAddress.DeliveryAddress getDeliveryAddress() {
                    return deliveryAddress;
                }

                /**
                 * Sets the value of the deliveryAddress property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BackgroundCheck.BackgroundSearchPackage.PersonalData.PostalAddress.DeliveryAddress }
                 *     
                 */
                public void setDeliveryAddress(BackgroundCheck.BackgroundSearchPackage.PersonalData.PostalAddress.DeliveryAddress value) {
                    this.deliveryAddress = value;
                }

                /**
                 * Gets the value of the type property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getType() {
                    return type;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setType(String value) {
                    this.type = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="StreetName" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "streetName"
                })
                public static class DeliveryAddress {

                    @XmlElement(name = "StreetName", required = true)
                    protected String streetName;

                    /**
                     * Gets the value of the streetName property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getStreetName() {
                        return streetName;
                    }

                    /**
                     * Sets the value of the streetName property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setStreetName(String value) {
                        this.streetName = value;
                    }

                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="IdValue">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "idValue"
        })
        public static class ReferenceId {

            @XmlElement(name = "IdValue", required = true)
            protected BackgroundCheck.BackgroundSearchPackage.ReferenceId.IdValue idValue;

            /**
             * Gets the value of the idValue property.
             * 
             * @return
             *     possible object is
             *     {@link BackgroundCheck.BackgroundSearchPackage.ReferenceId.IdValue }
             *     
             */
            public BackgroundCheck.BackgroundSearchPackage.ReferenceId.IdValue getIdValue() {
                return idValue;
            }

            /**
             * Sets the value of the idValue property.
             * 
             * @param value
             *     allowed object is
             *     {@link BackgroundCheck.BackgroundSearchPackage.ReferenceId.IdValue }
             *     
             */
            public void setIdValue(BackgroundCheck.BackgroundSearchPackage.ReferenceId.IdValue value) {
                this.idValue = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class IdValue {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "name")
                protected String name;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="AdditionalItems">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Text" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *                 &lt;attribute name="qualifier" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "additionalItems"
        })
        public static class Screenings {

            @XmlElement(name = "AdditionalItems", required = true)
            protected BackgroundCheck.BackgroundSearchPackage.Screenings.AdditionalItems additionalItems;

            /**
             * Gets the value of the additionalItems property.
             * 
             * @return
             *     possible object is
             *     {@link BackgroundCheck.BackgroundSearchPackage.Screenings.AdditionalItems }
             *     
             */
            public BackgroundCheck.BackgroundSearchPackage.Screenings.AdditionalItems getAdditionalItems() {
                return additionalItems;
            }

            /**
             * Sets the value of the additionalItems property.
             * 
             * @param value
             *     allowed object is
             *     {@link BackgroundCheck.BackgroundSearchPackage.Screenings.AdditionalItems }
             *     
             */
            public void setAdditionalItems(BackgroundCheck.BackgroundSearchPackage.Screenings.AdditionalItems value) {
                this.additionalItems = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Text" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *       &lt;attribute name="qualifier" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "text"
            })
            public static class AdditionalItems {

                @XmlElement(name = "Text", required = true)
                protected String text;
                @XmlAttribute(name = "qualifier")
                protected String qualifier;

                /**
                 * Gets the value of the text property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getText() {
                    return text;
                }

                /**
                 * Sets the value of the text property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setText(String value) {
                    this.text = value;
                }

                /**
                 * Gets the value of the qualifier property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getQualifier() {
                    return qualifier;
                }

                /**
                 * Sets the value of the qualifier property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setQualifier(String value) {
                    this.qualifier = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="CredentialType" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class PostBackURL {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "CredentialType")
        protected String credentialType;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the credentialType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCredentialType() {
            return credentialType;
        }

        /**
         * Sets the value of the credentialType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCredentialType(String value) {
            this.credentialType = value;
        }

    }

}
