//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.18 at 03:40:51 PM CDT 
//


package com.ccighgo.service.transport.partner.beans.partnerseasondetail;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PartnerSeasonNote complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PartnerSeasonNote">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="partnerSeasonId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="partnerSeasonNoteId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="partnerSeasonNoteTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="partnerSeasonNote" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="addedByPicUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="addedBy" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="addedOn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="privacy" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PartnerSeasonNote", propOrder = {
    "partnerSeasonId",
    "partnerSeasonNoteId",
    "partnerSeasonNoteTitle",
    "partnerSeasonNote",
    "addedByPicUrl",
    "addedBy",
    "addedOn",
    "privacy"
})
public class PartnerSeasonNote {

    protected int partnerSeasonId;
    protected int partnerSeasonNoteId;
    @XmlElement(required = true)
    protected String partnerSeasonNoteTitle;
    protected String partnerSeasonNote;
    @XmlElement(required = true)
    protected String addedByPicUrl;
    @XmlElement(required = true)
    protected String addedBy;
    @XmlElement(required = true)
    protected String addedOn;
    @XmlElement(required = true)
    protected String privacy;

    /**
     * Gets the value of the partnerSeasonId property.
     * 
     */
    public int getPartnerSeasonId() {
        return partnerSeasonId;
    }

    /**
     * Sets the value of the partnerSeasonId property.
     * 
     */
    public void setPartnerSeasonId(int value) {
        this.partnerSeasonId = value;
    }

    /**
     * Gets the value of the partnerSeasonNoteId property.
     * 
     */
    public int getPartnerSeasonNoteId() {
        return partnerSeasonNoteId;
    }

    /**
     * Sets the value of the partnerSeasonNoteId property.
     * 
     */
    public void setPartnerSeasonNoteId(int value) {
        this.partnerSeasonNoteId = value;
    }

    /**
     * Gets the value of the partnerSeasonNoteTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnerSeasonNoteTitle() {
        return partnerSeasonNoteTitle;
    }

    /**
     * Sets the value of the partnerSeasonNoteTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnerSeasonNoteTitle(String value) {
        this.partnerSeasonNoteTitle = value;
    }

    /**
     * Gets the value of the partnerSeasonNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnerSeasonNote() {
        return partnerSeasonNote;
    }

    /**
     * Sets the value of the partnerSeasonNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnerSeasonNote(String value) {
        this.partnerSeasonNote = value;
    }

    /**
     * Gets the value of the addedByPicUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddedByPicUrl() {
        return addedByPicUrl;
    }

    /**
     * Sets the value of the addedByPicUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddedByPicUrl(String value) {
        this.addedByPicUrl = value;
    }

    /**
     * Gets the value of the addedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddedBy() {
        return addedBy;
    }

    /**
     * Sets the value of the addedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddedBy(String value) {
        this.addedBy = value;
    }

    /**
     * Gets the value of the addedOn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddedOn() {
        return addedOn;
    }

    /**
     * Sets the value of the addedOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddedOn(String value) {
        this.addedOn = value;
    }

    /**
     * Gets the value of the privacy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrivacy() {
        return privacy;
    }

    /**
     * Sets the value of the privacy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrivacy(String value) {
        this.privacy = value;
    }

}
