//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 01:37:52 PM CST 
//


package com.ccighgo.service.transport.generic.beans.documents.Season;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.ccighgo.service.transport.common.response.beans.Response;


/**
 * <p>Java class for GenericSeasonDocument complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GenericSeasonDocument">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ccighgo.com/common}Response">
 *       &lt;sequence>
 *         &lt;element name="documentName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="uploaddedByFirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="uploadedByLastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="uploadedByPicUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="uploadedByDesignation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="documentDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="documentType" type="{http://www.ccighgo.com/genericseasonsdocuments}DocumentType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GenericSeasonDocument", propOrder = {
    "documentName",
    "uploaddedByFirstName",
    "uploadedByLastName",
    "uploadedByPicUrl",
    "uploadedByDesignation",
    "documentDescription",
    "documentType"
})
public class GenericSeasonDocument
    extends Response
{

    @XmlElement(required = true)
    protected String documentName;
    @XmlElement(required = true)
    protected String uploaddedByFirstName;
    @XmlElement(required = true)
    protected String uploadedByLastName;
    @XmlElement(required = true)
    protected String uploadedByPicUrl;
    @XmlElement(required = true)
    protected String uploadedByDesignation;
    @XmlElement(required = true)
    protected String documentDescription;
    @XmlElement(required = true)
    protected DocumentType documentType;

    /**
     * Gets the value of the documentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentName() {
        return documentName;
    }

    /**
     * Sets the value of the documentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentName(String value) {
        this.documentName = value;
    }

    /**
     * Gets the value of the uploaddedByFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUploaddedByFirstName() {
        return uploaddedByFirstName;
    }

    /**
     * Sets the value of the uploaddedByFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUploaddedByFirstName(String value) {
        this.uploaddedByFirstName = value;
    }

    /**
     * Gets the value of the uploadedByLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUploadedByLastName() {
        return uploadedByLastName;
    }

    /**
     * Sets the value of the uploadedByLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUploadedByLastName(String value) {
        this.uploadedByLastName = value;
    }

    /**
     * Gets the value of the uploadedByPicUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUploadedByPicUrl() {
        return uploadedByPicUrl;
    }

    /**
     * Sets the value of the uploadedByPicUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUploadedByPicUrl(String value) {
        this.uploadedByPicUrl = value;
    }

    /**
     * Gets the value of the uploadedByDesignation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUploadedByDesignation() {
        return uploadedByDesignation;
    }

    /**
     * Sets the value of the uploadedByDesignation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUploadedByDesignation(String value) {
        this.uploadedByDesignation = value;
    }

    /**
     * Gets the value of the documentDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentDescription() {
        return documentDescription;
    }

    /**
     * Sets the value of the documentDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentDescription(String value) {
        this.documentDescription = value;
    }

    /**
     * Gets the value of the documentType property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentType }
     *     
     */
    public DocumentType getDocumentType() {
        return documentType;
    }

    /**
     * Sets the value of the documentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentType }
     *     
     */
    public void setDocumentType(DocumentType value) {
        this.documentType = value;
    }

}
