//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.17 at 04:31:48 PM IST 
//


package com.ccighgo.service.transport.beans.fieldstaff.fieldstaffoverview;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FieldStaffDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FieldStaffDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fsGoId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="picUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="role" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="salutation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="homePhone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="workPhone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cellPhone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bestNumberHome" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="bestNumberWork" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="bestNumberCell" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="tollFreeNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fax" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="superRegion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="region" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="states" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="originalStartDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="totalPlacementManual" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="totalPlacementCalculated" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="totalPlacements" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="dateApplSubmitted" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dateApplApproved" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dateDOSTestTaken" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dateW9Recieved" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="approvedBy" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="loginId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="fieldStaffStatusId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FieldStaffDetails", propOrder = {
    "fsGoId",
    "firstName",
    "lastName",
    "picUrl",
    "role",
    "salutation",
    "homePhone",
    "workPhone",
    "cellPhone",
    "bestNumberHome",
    "bestNumberWork",
    "bestNumberCell",
    "tollFreeNumber",
    "fax",
    "email",
    "userName",
    "superRegion",
    "region",
    "states",
    "originalStartDate",
    "totalPlacementManual",
    "totalPlacementCalculated",
    "totalPlacements",
    "dateApplSubmitted",
    "dateApplApproved",
    "dateDOSTestTaken",
    "dateW9Recieved",
    "approvedBy",
    "loginId",
    "fieldStaffStatusId"
})
public class FieldStaffDetails {

    protected int fsGoId;
    @XmlElement(required = true)
    protected String firstName;
    @XmlElement(required = true)
    protected String lastName;
    @XmlElement(required = true)
    protected String picUrl;
    @XmlElement(required = true)
    protected String role;
    @XmlElement(required = true)
    protected String salutation;
    @XmlElement(required = true)
    protected String homePhone;
    @XmlElement(required = true)
    protected String workPhone;
    @XmlElement(required = true)
    protected String cellPhone;
    protected boolean bestNumberHome;
    protected boolean bestNumberWork;
    protected boolean bestNumberCell;
    @XmlElement(required = true)
    protected String tollFreeNumber;
    @XmlElement(required = true)
    protected String fax;
    @XmlElement(required = true)
    protected String email;
    @XmlElement(required = true)
    protected String userName;
    @XmlElement(required = true)
    protected String superRegion;
    @XmlElement(required = true)
    protected String region;
    protected String states;
    @XmlElement(required = true)
    protected String originalStartDate;
    protected int totalPlacementManual;
    protected int totalPlacementCalculated;
    protected int totalPlacements;
    @XmlElement(required = true)
    protected String dateApplSubmitted;
    @XmlElement(required = true)
    protected String dateApplApproved;
    @XmlElement(required = true)
    protected String dateDOSTestTaken;
    @XmlElement(required = true)
    protected String dateW9Recieved;
    @XmlElement(required = true)
    protected String approvedBy;
    protected int loginId;
    protected int fieldStaffStatusId;

    /**
     * Gets the value of the fsGoId property.
     * 
     */
    public int getFsGoId() {
        return fsGoId;
    }

    /**
     * Sets the value of the fsGoId property.
     * 
     */
    public void setFsGoId(int value) {
        this.fsGoId = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the picUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * Sets the value of the picUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPicUrl(String value) {
        this.picUrl = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRole(String value) {
        this.role = value;
    }

    /**
     * Gets the value of the salutation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalutation() {
        return salutation;
    }

    /**
     * Sets the value of the salutation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalutation(String value) {
        this.salutation = value;
    }

    /**
     * Gets the value of the homePhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHomePhone() {
        return homePhone;
    }

    /**
     * Sets the value of the homePhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHomePhone(String value) {
        this.homePhone = value;
    }

    /**
     * Gets the value of the workPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkPhone() {
        return workPhone;
    }

    /**
     * Sets the value of the workPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkPhone(String value) {
        this.workPhone = value;
    }

    /**
     * Gets the value of the cellPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCellPhone() {
        return cellPhone;
    }

    /**
     * Sets the value of the cellPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCellPhone(String value) {
        this.cellPhone = value;
    }

    /**
     * Gets the value of the bestNumberHome property.
     * 
     */
    public boolean isBestNumberHome() {
        return bestNumberHome;
    }

    /**
     * Sets the value of the bestNumberHome property.
     * 
     */
    public void setBestNumberHome(boolean value) {
        this.bestNumberHome = value;
    }

    /**
     * Gets the value of the bestNumberWork property.
     * 
     */
    public boolean isBestNumberWork() {
        return bestNumberWork;
    }

    /**
     * Sets the value of the bestNumberWork property.
     * 
     */
    public void setBestNumberWork(boolean value) {
        this.bestNumberWork = value;
    }

    /**
     * Gets the value of the bestNumberCell property.
     * 
     */
    public boolean isBestNumberCell() {
        return bestNumberCell;
    }

    /**
     * Sets the value of the bestNumberCell property.
     * 
     */
    public void setBestNumberCell(boolean value) {
        this.bestNumberCell = value;
    }

    /**
     * Gets the value of the tollFreeNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTollFreeNumber() {
        return tollFreeNumber;
    }

    /**
     * Sets the value of the tollFreeNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTollFreeNumber(String value) {
        this.tollFreeNumber = value;
    }

    /**
     * Gets the value of the fax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFax() {
        return fax;
    }

    /**
     * Sets the value of the fax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFax(String value) {
        this.fax = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the userName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    /**
     * Gets the value of the superRegion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuperRegion() {
        return superRegion;
    }

    /**
     * Sets the value of the superRegion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuperRegion(String value) {
        this.superRegion = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegion(String value) {
        this.region = value;
    }

    /**
     * Gets the value of the states property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStates() {
        return states;
    }

    /**
     * Sets the value of the states property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStates(String value) {
        this.states = value;
    }

    /**
     * Gets the value of the originalStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalStartDate() {
        return originalStartDate;
    }

    /**
     * Sets the value of the originalStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalStartDate(String value) {
        this.originalStartDate = value;
    }

    /**
     * Gets the value of the totalPlacementManual property.
     * 
     */
    public int getTotalPlacementManual() {
        return totalPlacementManual;
    }

    /**
     * Sets the value of the totalPlacementManual property.
     * 
     */
    public void setTotalPlacementManual(int value) {
        this.totalPlacementManual = value;
    }

    /**
     * Gets the value of the totalPlacementCalculated property.
     * 
     */
    public int getTotalPlacementCalculated() {
        return totalPlacementCalculated;
    }

    /**
     * Sets the value of the totalPlacementCalculated property.
     * 
     */
    public void setTotalPlacementCalculated(int value) {
        this.totalPlacementCalculated = value;
    }

    /**
     * Gets the value of the totalPlacements property.
     * 
     */
    public int getTotalPlacements() {
        return totalPlacements;
    }

    /**
     * Sets the value of the totalPlacements property.
     * 
     */
    public void setTotalPlacements(int value) {
        this.totalPlacements = value;
    }

    /**
     * Gets the value of the dateApplSubmitted property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateApplSubmitted() {
        return dateApplSubmitted;
    }

    /**
     * Sets the value of the dateApplSubmitted property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateApplSubmitted(String value) {
        this.dateApplSubmitted = value;
    }

    /**
     * Gets the value of the dateApplApproved property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateApplApproved() {
        return dateApplApproved;
    }

    /**
     * Sets the value of the dateApplApproved property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateApplApproved(String value) {
        this.dateApplApproved = value;
    }

    /**
     * Gets the value of the dateDOSTestTaken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateDOSTestTaken() {
        return dateDOSTestTaken;
    }

    /**
     * Sets the value of the dateDOSTestTaken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateDOSTestTaken(String value) {
        this.dateDOSTestTaken = value;
    }

    /**
     * Gets the value of the dateW9Recieved property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateW9Recieved() {
        return dateW9Recieved;
    }

    /**
     * Sets the value of the dateW9Recieved property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateW9Recieved(String value) {
        this.dateW9Recieved = value;
    }

    /**
     * Gets the value of the approvedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovedBy() {
        return approvedBy;
    }

    /**
     * Sets the value of the approvedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovedBy(String value) {
        this.approvedBy = value;
    }

    /**
     * Gets the value of the loginId property.
     * 
     */
    public int getLoginId() {
        return loginId;
    }

    /**
     * Sets the value of the loginId property.
     * 
     */
    public void setLoginId(int value) {
        this.loginId = value;
    }

    /**
     * Gets the value of the fieldStaffStatusId property.
     * 
     */
    public int getFieldStaffStatusId() {
        return fieldStaffStatusId;
    }

    /**
     * Sets the value of the fieldStaffStatusId property.
     * 
     */
    public void setFieldStaffStatusId(int value) {
        this.fieldStaffStatusId = value;
    }

}
