//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.14 at 12:09:40 PM CDT 
//


package com.ccighgo.service.transport.hostfamily.beans.application.photo.upload;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.ccighgo.service.transport.common.response.beans.Response;


/**
 * <p>Java class for HFApplicationUploadPhotos complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HFApplicationUploadPhotos">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ccighgo.com/common}Response">
 *       &lt;sequence>
 *         &lt;element name="loginId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="hfSeasonId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="fieldsFilled" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="percentUpdate" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="photos" type="{http://www.ccighgo.com/hfappphotos}Photos"/>
 *         &lt;element name="optionalPhotos" type="{http://www.ccighgo.com/hfappphotos}Photos"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HFApplicationUploadPhotos", propOrder = {
    "loginId",
    "hfSeasonId",
    "fieldsFilled",
    "percentUpdate",
    "photos",
    "optionalPhotos"
})
public class HFApplicationUploadPhotos
    extends Response
{

    protected int loginId;
    protected int hfSeasonId;
    protected int fieldsFilled;
    protected double percentUpdate;
    @XmlElement(required = true)
    protected Photos photos;
    @XmlElement(required = true)
    protected Photos optionalPhotos;

    /**
     * Gets the value of the loginId property.
     * 
     */
    public int getLoginId() {
        return loginId;
    }

    /**
     * Sets the value of the loginId property.
     * 
     */
    public void setLoginId(int value) {
        this.loginId = value;
    }

    /**
     * Gets the value of the hfSeasonId property.
     * 
     */
    public int getHfSeasonId() {
        return hfSeasonId;
    }

    /**
     * Sets the value of the hfSeasonId property.
     * 
     */
    public void setHfSeasonId(int value) {
        this.hfSeasonId = value;
    }

    /**
     * Gets the value of the fieldsFilled property.
     * 
     */
    public int getFieldsFilled() {
        return fieldsFilled;
    }

    /**
     * Sets the value of the fieldsFilled property.
     * 
     */
    public void setFieldsFilled(int value) {
        this.fieldsFilled = value;
    }

    /**
     * Gets the value of the percentUpdate property.
     * 
     */
    public double getPercentUpdate() {
        return percentUpdate;
    }

    /**
     * Sets the value of the percentUpdate property.
     * 
     */
    public void setPercentUpdate(double value) {
        this.percentUpdate = value;
    }

    /**
     * Gets the value of the photos property.
     * 
     * @return
     *     possible object is
     *     {@link Photos }
     *     
     */
    public Photos getPhotos() {
        return photos;
    }

    /**
     * Sets the value of the photos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Photos }
     *     
     */
    public void setPhotos(Photos value) {
        this.photos = value;
    }

    /**
     * Gets the value of the optionalPhotos property.
     * 
     * @return
     *     possible object is
     *     {@link Photos }
     *     
     */
    public Photos getOptionalPhotos() {
        return optionalPhotos;
    }

    /**
     * Sets the value of the optionalPhotos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Photos }
     *     
     */
    public void setOptionalPhotos(Photos value) {
        this.optionalPhotos = value;
    }

}
