//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.04 at 12:45:26 AM IST 
//


package com.ccighgo.service.transport.fieldstaff.beans.placement.adminerdplacement;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AdminERDPlacement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdminERDPlacement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="goId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fieldstaffFirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fieldstaffLastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="partner" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="season" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="program" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="holds" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="paxPhoto" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdminERDPlacement", propOrder = {
    "goId",
    "fieldstaffFirstName",
    "fieldstaffLastName",
    "firstName",
    "lastName",
    "partner",
    "country",
    "season",
    "program",
    "status",
    "holds",
    "paxPhoto"
})
public class AdminERDPlacement {

    @XmlElement(required = true)
    protected String goId;
    @XmlElement(required = true)
    protected String fieldstaffFirstName;
    @XmlElement(required = true)
    protected String fieldstaffLastName;
    @XmlElement(required = true)
    protected String firstName;
    @XmlElement(required = true)
    protected String lastName;
    @XmlElement(required = true)
    protected String partner;
    @XmlElement(required = true)
    protected String country;
    @XmlElement(required = true)
    protected String season;
    @XmlElement(required = true)
    protected String program;
    @XmlElement(required = true)
    protected String status;
    @XmlElement(required = true)
    protected String holds;
    @XmlElement(required = true)
    protected String paxPhoto;

    /**
     * Gets the value of the goId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGoId() {
        return goId;
    }

    /**
     * Sets the value of the goId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGoId(String value) {
        this.goId = value;
    }

    /**
     * Gets the value of the fieldstaffFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldstaffFirstName() {
        return fieldstaffFirstName;
    }

    /**
     * Sets the value of the fieldstaffFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldstaffFirstName(String value) {
        this.fieldstaffFirstName = value;
    }

    /**
     * Gets the value of the fieldstaffLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldstaffLastName() {
        return fieldstaffLastName;
    }

    /**
     * Sets the value of the fieldstaffLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldstaffLastName(String value) {
        this.fieldstaffLastName = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the partner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartner() {
        return partner;
    }

    /**
     * Sets the value of the partner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartner(String value) {
        this.partner = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the season property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeason() {
        return season;
    }

    /**
     * Sets the value of the season property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeason(String value) {
        this.season = value;
    }

    /**
     * Gets the value of the program property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgram() {
        return program;
    }

    /**
     * Sets the value of the program property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgram(String value) {
        this.program = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the holds property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHolds() {
        return holds;
    }

    /**
     * Sets the value of the holds property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHolds(String value) {
        this.holds = value;
    }

    /**
     * Gets the value of the paxPhoto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaxPhoto() {
        return paxPhoto;
    }

    /**
     * Sets the value of the paxPhoto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaxPhoto(String value) {
        this.paxPhoto = value;
    }

}
