//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.13 at 02:09:50 PM CST 
//


package com.ccighgo.service.transport.fieldstaff.beans.fieldstaffparticipant;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ccighgo.service.transport.fieldstaff.beans.fieldstaffparticipant package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FieldStaffParticipants_QNAME = new QName("http://www.ccighgo.com/fsoverview", "FieldStaffParticipants");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ccighgo.service.transport.fieldstaff.beans.fieldstaffparticipant
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FieldStaffParticipants }
     * 
     */
    public FieldStaffParticipants createFieldStaffParticipants() {
        return new FieldStaffParticipants();
    }

    /**
     * Create an instance of {@link FieldStaffParticipant }
     * 
     */
    public FieldStaffParticipant createFieldStaffParticipant() {
        return new FieldStaffParticipant();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FieldStaffParticipants }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ccighgo.com/fsoverview", name = "FieldStaffParticipants")
    public JAXBElement<FieldStaffParticipants> createFieldStaffParticipants(FieldStaffParticipants value) {
        return new JAXBElement<FieldStaffParticipants>(_FieldStaffParticipants_QNAME, FieldStaffParticipants.class, null, value);
    }

}
