//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.07 at 12:04:22 PM CDT 
//


package com.ccighgo.service.transport.hostfamily.beans.application.familylifestyle;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HFFamilyDayDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HFFamilyDayDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="household" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="typicalWeekdayAtHome" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="typicalWeekendAtHome" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="favouriteThingsToDoAsFamily" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HFFamilyDayDetails", propOrder = {
    "household",
    "typicalWeekdayAtHome",
    "typicalWeekendAtHome",
    "favouriteThingsToDoAsFamily"
})
public class HFFamilyDayDetails {

    @XmlElement(required = true)
    protected String household;
    @XmlElement(required = true)
    protected String typicalWeekdayAtHome;
    @XmlElement(required = true)
    protected String typicalWeekendAtHome;
    @XmlElement(required = true)
    protected String favouriteThingsToDoAsFamily;

    /**
     * Gets the value of the household property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHousehold() {
        return household;
    }

    /**
     * Sets the value of the household property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHousehold(String value) {
        this.household = value;
    }

    /**
     * Gets the value of the typicalWeekdayAtHome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypicalWeekdayAtHome() {
        return typicalWeekdayAtHome;
    }

    /**
     * Sets the value of the typicalWeekdayAtHome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypicalWeekdayAtHome(String value) {
        this.typicalWeekdayAtHome = value;
    }

    /**
     * Gets the value of the typicalWeekendAtHome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypicalWeekendAtHome() {
        return typicalWeekendAtHome;
    }

    /**
     * Sets the value of the typicalWeekendAtHome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypicalWeekendAtHome(String value) {
        this.typicalWeekendAtHome = value;
    }

    /**
     * Gets the value of the favouriteThingsToDoAsFamily property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFavouriteThingsToDoAsFamily() {
        return favouriteThingsToDoAsFamily;
    }

    /**
     * Sets the value of the favouriteThingsToDoAsFamily property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFavouriteThingsToDoAsFamily(String value) {
        this.favouriteThingsToDoAsFamily = value;
    }

}
