//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.12 at 02:55:31 PM CST 
//


package com.ccighgo.service.transport.partner.beans.admin.add.partner;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ccighgo.service.transport.partner.beans.admin.add.partner package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AdminAddPartner_QNAME = new QName("http://www.ccighgo.com/adminaddpartner", "AdminAddPartner");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ccighgo.service.transport.partner.beans.admin.add.partner
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AdminAddPartner }
     * 
     */
    public AdminAddPartner createAdminAddPartner() {
        return new AdminAddPartner();
    }

    /**
     * Create an instance of {@link CCIContact }
     * 
     */
    public CCIContact createCCIContact() {
        return new CCIContact();
    }

    /**
     * Create an instance of {@link NoteTags }
     * 
     */
    public NoteTags createNoteTags() {
        return new NoteTags();
    }

    /**
     * Create an instance of {@link NoteTopics }
     * 
     */
    public NoteTopics createNoteTopics() {
        return new NoteTopics();
    }

    /**
     * Create an instance of {@link Note }
     * 
     */
    public Note createNote() {
        return new Note();
    }

    /**
     * Create an instance of {@link Creator }
     * 
     */
    public Creator createCreator() {
        return new Creator();
    }

    /**
     * Create an instance of {@link Topic }
     * 
     */
    public Topic createTopic() {
        return new Topic();
    }

    /**
     * Create an instance of {@link Salutation }
     * 
     */
    public Salutation createSalutation() {
        return new Salutation();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdminAddPartner }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ccighgo.com/adminaddpartner", name = "AdminAddPartner")
    public JAXBElement<AdminAddPartner> createAdminAddPartner(AdminAddPartner value) {
        return new JAXBElement<AdminAddPartner>(_AdminAddPartner_QNAME, AdminAddPartner.class, null, value);
    }

}
