//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.03 at 10:05:36 AM CDT 
//


package com.ccighgo.service.transport.partner.beans.country.partneruser;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PartnerWorkQueueCategory complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PartnerWorkQueueCategory">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="partnerId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="partnerWorkQueueCategoryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="partnerWorkQueueCategoryNo" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PartnerWorkQueueCategory", propOrder = {
    "partnerId",
    "partnerWorkQueueCategoryName",
    "partnerWorkQueueCategoryNo"
})
public class PartnerWorkQueueCategory {

    protected int partnerId;
    @XmlElement(required = true)
    protected String partnerWorkQueueCategoryName;
    protected int partnerWorkQueueCategoryNo;

    /**
     * Gets the value of the partnerId property.
     * 
     */
    public int getPartnerId() {
        return partnerId;
    }

    /**
     * Sets the value of the partnerId property.
     * 
     */
    public void setPartnerId(int value) {
        this.partnerId = value;
    }

    /**
     * Gets the value of the partnerWorkQueueCategoryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnerWorkQueueCategoryName() {
        return partnerWorkQueueCategoryName;
    }

    /**
     * Sets the value of the partnerWorkQueueCategoryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnerWorkQueueCategoryName(String value) {
        this.partnerWorkQueueCategoryName = value;
    }

    /**
     * Gets the value of the partnerWorkQueueCategoryNo property.
     * 
     */
    public int getPartnerWorkQueueCategoryNo() {
        return partnerWorkQueueCategoryNo;
    }

    /**
     * Sets the value of the partnerWorkQueueCategoryNo property.
     * 
     */
    public void setPartnerWorkQueueCategoryNo(int value) {
        this.partnerWorkQueueCategoryNo = value;
    }

}
